package com.cevr.business.model.entity;
// Generated 2017-6-10 13:36:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BizCar1001 generated by hbm2java
 */
@Entity
@Table(name = "biz_car_1001", catalog = "cevr")
public class BizCar1001 implements java.io.Serializable {

	private String id;
	private String carName;
	private String carNickname;
	private String carInfo;
	private String carNo;
	private String groupId;
	private String deleteflag;
	private String cancleflag;
	private String holdflag;
	private Date createtime;
	private Date updatetime;
	private String operatorId;

	public BizCar1001() {
	}

	public BizCar1001(String id, String carName) {
		this.id = id;
		this.carName = carName;
	}

	public BizCar1001(String id, String carName, String carNickname, String carInfo, String carNo, String groupId,
			String deleteflag, String cancleflag, String holdflag, Date createtime, Date updatetime,
			String operatorId) {
		this.id = id;
		this.carName = carName;
		this.carNickname = carNickname;
		this.carInfo = carInfo;
		this.carNo = carNo;
		this.groupId = groupId;
		this.deleteflag = deleteflag;
		this.cancleflag = cancleflag;
		this.holdflag = holdflag;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.operatorId = operatorId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "car_name", nullable = false, length = 50)
	public String getCarName() {
		return this.carName;
	}

	public void setCarName(String carName) {
		this.carName = carName;
	}

	@Column(name = "car_nickname", length = 50)
	public String getCarNickname() {
		return this.carNickname;
	}

	public void setCarNickname(String carNickname) {
		this.carNickname = carNickname;
	}

	@Column(name = "car_info", length = 500)
	public String getCarInfo() {
		return this.carInfo;
	}

	public void setCarInfo(String carInfo) {
		this.carInfo = carInfo;
	}

	@Column(name = "car_no", length = 100)
	public String getCarNo() {
		return this.carNo;
	}

	public void setCarNo(String carNo) {
		this.carNo = carNo;
	}

	@Column(name = "group_id", length = 30)
	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	@Column(name = "deleteflag", length = 2)
	public String getDeleteflag() {
		return this.deleteflag;
	}

	public void setDeleteflag(String deleteflag) {
		this.deleteflag = deleteflag;
	}

	@Column(name = "cancleflag", length = 2)
	public String getCancleflag() {
		return this.cancleflag;
	}

	public void setCancleflag(String cancleflag) {
		this.cancleflag = cancleflag;
	}

	@Column(name = "holdflag", length = 2)
	public String getHoldflag() {
		return this.holdflag;
	}

	public void setHoldflag(String holdflag) {
		this.holdflag = holdflag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatetime", length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "operator_id", length = 20)
	public String getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

}
