package com.cevr.business.model.entity;
// Generated 2017-6-8 16:11:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BizTicketPeople generated by hbm2java
 */
@Entity(name = "biz_ticket_people")
public class BizTicketPeople implements java.io.Serializable {

	private String id;
	private String userName;
	private String userTel;
	private String userSex;
	private String userEmail;
	private String deleteflag;
	private String cancleflag;
	private String holdflag;
	private Date createtime;
	private Date updatetime;
	private String operatorId;

	public BizTicketPeople() {
	}

	public BizTicketPeople(String id) {
		this.id = id;
	}

	public BizTicketPeople(String id, String userName, String userTel, String userSex, String userEmail,
			String deleteflag, String cancleflag, String holdflag, Date createtime, Date updatetime,
			String operatorId) {
		this.id = id;
		this.userName = userName;
		this.userTel = userTel;
		this.userSex = userSex;
		this.userEmail = userEmail;
		this.deleteflag = deleteflag;
		this.cancleflag = cancleflag;
		this.holdflag = holdflag;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.operatorId = operatorId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 30)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "user_name", length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_tel", length = 20)
	public String getUserTel() {
		return this.userTel;
	}

	public void setUserTel(String userTel) {
		this.userTel = userTel;
	}

	@Column(name = "user_sex", length = 5)
	public String getUserSex() {
		return this.userSex;
	}

	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	@Column(name = "user_email", length = 50)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "deleteflag", length = 2)
	public String getDeleteflag() {
		return this.deleteflag;
	}

	public void setDeleteflag(String deleteflag) {
		this.deleteflag = deleteflag;
	}

	@Column(name = "cancleflag", length = 2)
	public String getCancleflag() {
		return this.cancleflag;
	}

	public void setCancleflag(String cancleflag) {
		this.cancleflag = cancleflag;
	}

	@Column(name = "holdflag", length = 2)
	public String getHoldflag() {
		return this.holdflag;
	}

	public void setHoldflag(String holdflag) {
		this.holdflag = holdflag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatetime", length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "operator_id", length = 20)
	public String getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

}
