package com.cevr.business.model.entity;
// Generated 2017-6-12 9:00:05 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DicImgType9001 generated by hbm2java
 */
@Entity
@Table(name = "dic_img_type_9001", catalog = "cevr")
public class DicImgType9001 implements java.io.Serializable {
    
    private String id;
    
    private String typeName;
    
    private String typeInfo;
    
    private String deleteflag;
    
    private String cancleflag;
    
    private String holdflag;
    
    private Date createtime;
    
    private Date updatetime;
    
    private String operatorId;
    
    public DicImgType9001() {
    }
    
    public DicImgType9001(String id) {
        this.id = id;
    }
    
    public DicImgType9001(String id, String typeName, String typeInfo, String deleteflag, String cancleflag, String holdflag, Date createtime, Date updatetime, String operatorId) {
        this.id = id;
        this.typeName = typeName;
        this.typeInfo = typeInfo;
        this.deleteflag = deleteflag;
        this.cancleflag = cancleflag;
        this.holdflag = holdflag;
        this.createtime = createtime;
        this.updatetime = updatetime;
        this.operatorId = operatorId;
    }
    
    @Id
    
    @Column(name = "id", unique = true, nullable = false, length = 50)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name = "type_name", length = 100)
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    
    @Column(name = "type_info", length = 200)
    public String getTypeInfo() {
        return this.typeInfo;
    }
    
    public void setTypeInfo(String typeInfo) {
        this.typeInfo = typeInfo;
    }
    
    @Column(name = "deleteflag", length = 2)
    public String getDeleteflag() {
        return this.deleteflag;
    }
    
    public void setDeleteflag(String deleteflag) {
        this.deleteflag = deleteflag;
    }
    
    @Column(name = "cancleflag", length = 2)
    public String getCancleflag() {
        return this.cancleflag;
    }
    
    public void setCancleflag(String cancleflag) {
        this.cancleflag = cancleflag;
    }
    
    @Column(name = "holdflag", length = 2)
    public String getHoldflag() {
        return this.holdflag;
    }
    
    public void setHoldflag(String holdflag) {
        this.holdflag = holdflag;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "createtime", length = 19)
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updatetime", length = 19)
    public Date getUpdatetime() {
        return this.updatetime;
    }
    
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
    
    @Column(name = "operator_id", length = 50)
    public String getOperatorId() {
        return this.operatorId;
    }
    
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId;
    }
    
}
