package com.gomyck.business.model.entity;
// Generated 2017-6-12 9:00:05 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BizCarVideo1004 generated by hbm2java
 */
@Entity
@Table(name = "biz_car_video_1004", catalog = "cevr")
public class BizCarVideo1004 implements java.io.Serializable {
    
    private String id;
    
    private String carId;
    
    private String src;
    
    private String deleteflag;
    
    private String cancleflag;
    
    private String holdflag;
    
    private Date createtime;
    
    private Date updatetime;
    
    public BizCarVideo1004() {
    }
    
    public BizCarVideo1004(String id, String carId, String src) {
        this.id = id;
        this.carId = carId;
        this.src = src;
    }
    
    public BizCarVideo1004(String id, String carId, String src, String deleteflag, String cancleflag, String holdflag, Date createtime, Date updatetime) {
        this.id = id;
        this.carId = carId;
        this.src = src;
        this.deleteflag = deleteflag;
        this.cancleflag = cancleflag;
        this.holdflag = holdflag;
        this.createtime = createtime;
        this.updatetime = updatetime;
    }
    
    @Id
    
    @Column(name = "id", unique = true, nullable = false, length = 50)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name = "car_id", nullable = false, length = 50)
    public String getCarId() {
        return this.carId;
    }
    
    public void setCarId(String carId) {
        this.carId = carId;
    }
    
    @Column(name = "src", nullable = false, length = 2000)
    public String getSrc() {
        return this.src;
    }
    
    public void setSrc(String src) {
        this.src = src;
    }
    
    @Column(name = "deleteflag", length = 2)
    public String getDeleteflag() {
        return this.deleteflag;
    }
    
    public void setDeleteflag(String deleteflag) {
        this.deleteflag = deleteflag;
    }
    
    @Column(name = "cancleflag", length = 2)
    public String getCancleflag() {
        return this.cancleflag;
    }
    
    public void setCancleflag(String cancleflag) {
        this.cancleflag = cancleflag;
    }
    
    @Column(name = "holdflag", length = 2)
    public String getHoldflag() {
        return this.holdflag;
    }
    
    public void setHoldflag(String holdflag) {
        this.holdflag = holdflag;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "createtime", length = 19)
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updatetime", length = 19)
    public Date getUpdatetime() {
        return this.updatetime;
    }
    
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
    
}
