package com.gomyck.business.model.entity;
// Generated 2017-6-12 9:00:05 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BizTicket2001 generated by hbm2java
 */
@Entity
@Table(name = "biz_ticket_2001", catalog = "cevr")
public class BizTicket2001 implements java.io.Serializable {

	private String id;
	private String fromIp;
	private Date clickTime;
	private int ticketNum;
	private String ticketTypeId;
	private String clickPeopleId;
	private String clickCarId;
	private String deleteflag;
	private String cancleflag;
	private String holdflag;
	private Date createtime;
	private Date updatetime;
	private String operatorId;

	public BizTicket2001() {
	}

	public BizTicket2001(String id, int ticketNum, String clickPeopleId, String clickCarId) {
		this.id = id;
		this.ticketNum = ticketNum;
		this.clickPeopleId = clickPeopleId;
		this.clickCarId = clickCarId;
	}

	public BizTicket2001(String id, String fromIp, Date clickTime, int ticketNum, String ticketTypeId,
			String clickPeopleId, String clickCarId, String deleteflag, String cancleflag, String holdflag,
			Date createtime, Date updatetime, String operatorId) {
		this.id = id;
		this.fromIp = fromIp;
		this.clickTime = clickTime;
		this.ticketNum = ticketNum;
		this.ticketTypeId = ticketTypeId;
		this.clickPeopleId = clickPeopleId;
		this.clickCarId = clickCarId;
		this.deleteflag = deleteflag;
		this.cancleflag = cancleflag;
		this.holdflag = holdflag;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.operatorId = operatorId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "from_ip", length = 30)
	public String getFromIp() {
		return this.fromIp;
	}

	public void setFromIp(String fromIp) {
		this.fromIp = fromIp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "click_time", length = 19)
	public Date getClickTime() {
		return this.clickTime;
	}

	public void setClickTime(Date clickTime) {
		this.clickTime = clickTime;
	}

	@Column(name = "ticket_num", nullable = false)
	public int getTicketNum() {
		return this.ticketNum;
	}

	public void setTicketNum(int ticketNum) {
		this.ticketNum = ticketNum;
	}

	@Column(name = "ticket_type_id", length = 50)
	public String getTicketTypeId() {
		return this.ticketTypeId;
	}

	public void setTicketTypeId(String ticketTypeId) {
		this.ticketTypeId = ticketTypeId;
	}

	@Column(name = "click_people_id", nullable = false, length = 50)
	public String getClickPeopleId() {
		return this.clickPeopleId;
	}

	public void setClickPeopleId(String clickPeopleId) {
		this.clickPeopleId = clickPeopleId;
	}

	@Column(name = "click_car_id", nullable = false, length = 50)
	public String getClickCarId() {
		return this.clickCarId;
	}

	public void setClickCarId(String clickCarId) {
		this.clickCarId = clickCarId;
	}

	@Column(name = "deleteflag", length = 2)
	public String getDeleteflag() {
		return this.deleteflag;
	}

	public void setDeleteflag(String deleteflag) {
		this.deleteflag = deleteflag;
	}

	@Column(name = "cancleflag", length = 2)
	public String getCancleflag() {
		return this.cancleflag;
	}

	public void setCancleflag(String cancleflag) {
		this.cancleflag = cancleflag;
	}

	@Column(name = "holdflag", length = 2)
	public String getHoldflag() {
		return this.holdflag;
	}

	public void setHoldflag(String holdflag) {
		this.holdflag = holdflag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatetime", length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "operator_id", length = 50)
	public String getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

}
